// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TorrentOptions } from "./TorrentOptions";

export type Config = { bind_address: string, password: string, username: string, token: string | null, db_path: string, session_path: string, torrent_options: TorrentOptions, output_path: string, };
